import {hash} from '../realtor-naver-blog/scripts/lib/contracts.mjs';
import {officeFingerprint} from '../realtor-naver-blog/scripts/lib/content.mjs';
export const office = {display_name:'테스트 사무소', public_contact:'000-0000-0000'};
export const scenarios = [
  {type:'아파트', location:'강남', condition:'공급 31평, 방 3개', target:'생활 공간과 방 배치를 비교하는 실거주 수요', intent:'강남에서 방을 나누어 쓸 아파트를 찾는가?', keyword:'강남 아파트 매매', sections:['방 배치가 생활에 맞는가?', '총 비용은 확인됐는가?'], cta:'보유 가구에 맞는 방 배치와 총 비용 확인'},
  {type:'빌라', location:'대학가', condition:'1.5룸, 보증금 500만 원, 월세 40만 원, 책상 제공', target:'생활 준비 비용을 줄이려는 대학 인근 거주 수요', intent:'대학가에서 초기 비용과 가구 준비를 줄일 수 있는가?', keyword:'대학가 가구 있는 빌라 월세', sections:['준비할 가구는 무엇인가?', '월 부담 비용은 얼마인가?'], cta:'보유 짐 기준 필요한 가구와 관리비 포함 항목 확인'},
  {type:'상가', location:'역 인근', condition:'1층, 전용 30㎡, 개별 출입구', target:'소규모 점포의 출입 동선과 면적을 비교하는 운영자', intent:'역 인근에서 개별 출입구가 있는 작은 점포를 찾는가?', keyword:'역 인근 1층 상가 임대', sections:['출입 동선은 어떻게 되는가?', '요청 업종의 설비 조건은 확인됐는가?'], cta:'예정 업종에 필요한 설비와 임대 조건 확인'},
  {type:'창고', location:'파주', condition:'면적 200㎡, 층고 6m, 5톤 차량 진입 확인', target:'차량 진입과 상하차를 우선하는 재고 운영자', intent:'파주에서 보유 차량이 진입하는 창고를 찾는가?', keyword:'파주 차량 진입 창고 임대', sections:['차량 규격에 맞는가?', '내부 보관 공간은 어떻게 구성하는가?'], cta:'차량 규격에 따른 회차와 상하차 조건 확인'},
  {type:'토지', location:'제주 해안가', condition:'면적 400㎡, 지목 전', target:'해안가 토지의 현장 조건을 비교하는 매수 검토자', intent:'제주 해안가 토지의 현장과 이용 조건은 무엇인가?', keyword:'제주 해안가 토지 매매', sections:['확인된 현장 조건은 무엇인가?', '희망 활용에 필요한 추가 확인은 무엇인가?'], cta:'희망 활용을 기준으로 도로와 용도지역 확인'},
];
export function fixture(scenario = scenarios[0]) {
  const transaction = ['상가','창고','빌라'].includes(scenario.type) ? '임대' : '매매';
  const values = {type:scenario.type, transaction, location:scenario.location, conditions:scenario.condition};
  const listing = {schema_version:'1.0', property_type:scenario.type, transaction, type_fact_id:'type', transaction_fact_id:'transaction', sources:[{id:'input',kind:'user',locator:'test fixture only',excerpt:Object.values(values).join('; ')}], facts:Object.entries(values).map(([id,value])=>({id,label:id,value,status:'confirmed',source_ids:['input']})), unknowns:['관리 및 이용 조건 추가 확인'], photos:[]};
  const strategy = {schema_version:'1.0',seo_mode:'inferred_candidates',interpretation:{text:scenario.condition,fact_ids:['type','transaction','conditions']},primary_target:{text:scenario.target,reason:scenario.condition,fact_ids:['conditions','location']},search_intent:scenario.intent,keywords:{label:'추천 후보',main:scenario.keyword,related:[scenario.location+' '+scenario.type,scenario.type+' 조건 확인']},hook:{text:scenario.condition,fact_ids:['conditions']},title_direction:scenario.intent,intro_direction:scenario.sections[0],sections:scenario.sections.map((q,i)=>({id:'s'+i,question:q,direction:q,fact_ids:['conditions'],photo_ids:[]})),cta:{benefit:scenario.cta,channel:'phone'},checks:[...listing.unknowns]};
  const post = {schema_version:'1.0',strategy_hash:hash(strategy),fact_review:{completed:true,notes:'Synthetic fixture; asserted numbers are present in cited inputs.'},style:{origin:'default',summary:'차분한 존댓말'},title:{text:scenario.location+' '+scenario.type+' 조건 안내',fact_ids:['location','type']},blocks:[{type:'paragraph',text:scenario.intent,fact_ids:['location','type']},{type:'image',role:'thumbnail',path:'sample.png',alt:'테스트 썸네일',reviewed:true},...scenario.sections.map((q,i)=>({type:'heading',text:q,fact_ids:[],section_id:'s'+i})),{type:'paragraph',text:scenario.condition,fact_ids:['conditions']},{type:'table',rows:[{label:'확인된 조건',text:scenario.condition,fact_ids:['conditions']}]},{type:'image',role:'cta_banner',path:'sample.png',alt:'테스트 상담 배너',reviewed:true,office_hash:officeFingerprint(office)},{type:'cta',text:scenario.cta+'을 안내합니다.',benefit:scenario.cta,fact_ids:[]}],map_omission_reason:'테스트 입력에 상세 위치 없음'};
  post.listing_hash = hash(listing);
  return {listing,strategy,post};
}
